# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/first_nbdev',
                'doc_host': 'https://erozon.github.io',
                'git_url': 'https://github.com/erozon/first_nbdev',
                'lib_path': 'first_nbdev'},
  'syms': {'first_nbdev.core': {'first_nbdev.core.foo': ('core.html#foo', 'first_nbdev/core.py')}}}
